# AnvilRepair configuration file by dev-stan and bobby29831
# You can find the configuration file for the latest versions here:
# Do not change this!
config-version: 1.3.0

# Set this to false to disable WorldGuard checks on region
worldguard-enabled: true

# Basic plugin settings
repair:

  # Items used to repair an anvil
  items:
    - IRON_BLOCK
    - DAMANGED_ANVIL
    - CHIPPED_ANVIL
    - ANVIL
  amount: 1 # Amount of material needed to repair the anvil

effects:
  enabled: true # Set to false if you want to disable effects
  size: 1 # Default is 1
  density: 25 # Default is 25
  color: # Standard RGB color scheme
    r: 69
    g: 69
    b: 69

  # Sound which is played on anvil fix
  playsound:
    enabled: true # Whether to play sound on repair
    sound: BLOCK_ANVIL_HIT # https://www.spigotmc.org/wiki/cc-sounds-list/
    volume: 3.0 # Default is 3.0
    pitch: 5.0 # Default is 5.0
