# AnvilRepair configuration file by dev-stan
# You can find the configuration file for the latest versions here:
# Do not change this!
config-version: 1.2.2

# Set this to false to disable all plugin features. If a "plugin is disabled" message shows up even though the option below is set to "true"
# Update to the latest version and check for compatibility with other plugins.
enable-plugin: true

# Basic plugin settings
repair:

  # Items used to repair an anvil
  items:
    - IRON_BLOCK
    - DAMANGED_ANVIL
    - CHIPPED_ANVIL
    - ANVIL
  amount: 1 # Amount of material needed to repair the anvil

# Configurable commands, make sure the names are compatible with other plugins (for example don't set main to: "essentials", "luckperms").
# Reload the server to see the changes.
commands:
# Main command used for other subcommands.
  enabled: true

# Configurable messages, set the message to "-1" in order to send nothing (prefix, suffix). 
# Reload the server to see the changes.
messages:

  # Default messages, used the most.
  default:
    prefix: "&8[&7Anvil Repair&8]: &7"
    
  # Plugin warnings, by default all set to true, only change if plugin is spamming console.
  errors:
    enabled: true
    show-errors-console: true
    show-errors-op: true

# Configurable permisisons
# Reload the server to see the changes.
permissions:
  use: "arepair.use"
  no-price: "arepair.no-price"
  admin: "arepair.admin"

effects:
  enabled: true # Set to false if you want to disable effects
  size: 1 # Default is 1
  density: 25 # Default is 25
  
  # Sound which is played on anvil fix
  playsound:
   enabled: true # Wether to play sound on repair
   sound: BLOCK_ANVIL_HIT # https://www.spigotmc.org/wiki/cc-sounds-list/
   volume: 3.0 # Default is 3.0
   pitch: 5.0 # Default is 5.0
